###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: abms-memcached

    redis:
      image: redis:alpine
      container_name: abms-redis

    mariadb:
      image: mariadb:10.1
      container_name: abms-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=innocom888273374
        - MYSQL_DATABASE=abms
        - MYSQL_USER=abms
        - MYSQL_PASSWORD=innocom888273374
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: abms-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: abms-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

